version: '3.9'

services:
  jenkins:
    build: .
    image: jenkins-terraform-gcp:1.1
    container_name: jenkins-terraform-gcp
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./gcp-sa-key.json:/var/jenkins_home/gcp-sa-key.json:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/var/jenkins_home/gcp-sa-key.json
      - TF_IN_AUTOMATION=true
      - TF_INPUT=false
      - TF_LOG=INFO
      - PROJECT_ID=gcp-dev-july-2026
      - REGION=us-central1
      - ZONE=us-central1-a
    restart: unless-stopped

volumes:
  jenkins_home:
